spring:
  application:
    name: curitas-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/curitas_api}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  web:
    error:
      include-stacktrace: never

api:
  security:
    token:
      secret: ${JWT_SECRET:12345678}

